name: Backend CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies for all services
      run: |
        cd authentification-service && npm ci
        cd ../administrateur-service && npm ci
        cd ../metier-service && npm ci
        cd ../iot-service && npm ci
    
    - name: Lint authentification-service
      run: cd authentification-service && npm run lint || true
    
    - name: Lint administrateur-service
      run: cd administrateur-service && npm run lint || true
    
    - name: Lint metier-service
      run: cd metier-service && npm run lint || true
    
    - name: Lint iot-service
      run: cd iot-service && npm run lint || true
    
    - name: Test authentification-service
      run: cd authentification-service && npm test || true
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    - name: Test administrateur-service
      run: cd administrateur-service && npm test || true
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
    
    - name: Test metier-service
      run: cd metier-service && npm test || true
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
    
    - name: Test iot-service
      run: cd iot-service && npm test || true
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }} 